### ISSUE TITLE
关于FGOAssetsModifyTool的使用 出现了如下的报错（因为隔壁貌似咩办法提问了，我就写在这边了）

### ISSUE THREAD

**Issue by Thunderltx** [nishuoshenme/fgoUnlockFPS#24]
实际环境：
clone 最新的FGOAssetsModifyTool
日服资源包
VS2022
.NET6.0
实际情况：
输入【2】进行解密后，报错
报错内容如下：
Decrypt: E:\FGOAssetsModifyTool-master\FGOAssetsModifyTool\bin\Debug\net6.0\Android\2135f3a7de76270de48534275de11f431094237b.bin
pad block corrupted
   at Org.BouncyCastle.Crypto.Paddings.Pkcs7Padding.PadCount(Byte[] input)
   at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff)
   at FGOAssetsModifyTool.CatAndMouseGame.MouseHomeMain(Byte[] data, Byte[] home, Byte[] info, Boolean isCompress) in E:\FGOAssetsModifyTool-master\FGOAssetsModifyTool\CatAndMouseGame.cs:line 304
MouseHomeMain failed
Value cannot be null. (Parameter 'bytes')
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at FGOAssetsModifyTool.Program.DisplayMenuAsync() in E:\FGOAssetsModifyTool-master\FGOAssetsModifyTool\Program.cs:line 63

貌似自从日服这次新活动开始，就没办法正常使用FGOAssetsModifyTool 对资源进行解密了
不知道作者肯否能答疑解惑

**Comment by hexstr** [comment]
~~我没测试，多半是我把代码写错了，用我发布的[Release(https://github.com/hexstr/FGOAssetsModifyTool/releases)~~  
看来不是代码问题

**Comment by hexstr** [comment]
不管了懒得分析，我把repo打开看看有没有人贡献代码
